name: Rebuilder

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuilder Prod
        run: curl -X GET "${{ secrets.PROD_REDEPLOY_URL }}"
      - name: Rebuilder Dev
        run: curl -X GET "${{ secrets.DEV_REDEPLOY_URL }}"